### ISSUE TITLE
cpu doubles when I use this extension compare with the original youtube playback.

### ISSUE THREAD

**Issue by rsyqvthv** [1natsu172/Outside-YouTube-Player-Bar#53]
when I use original youtube playback a video, it shows my cpu runs in 6%
but when I active this this bar extension to play same video, cpu will raise to 11% - 17%

the cpu will low down to 2% when I pause the youtube, with or without extension, 
so I think it must something when active this extension has doubled the cpu usage when playback.

Would you confirm to us if this is design to be like this? or it's can be adjust to make it lower cpu usage?

Thanks!!

**Comment by 1natsu172** [comment]
@rsyqvthv 

The CPU problem is partly due to this extension, but the root cause lies in YouTube's specifications.

Regardless of whether this extension is enabled or not, YouTube uses a significant amount of CPU while the player bar is displayed. This is likely due to the movement of the seek bar and various other processes that are taking place. As a test, try disabling this extension and keep moving the mouse cursor over the video to keep the player bar constantly displayed. You should be able to confirm that the CPU usage spikes. When you stop moving the mouse and the player bar disappears, the CPU usage will calm down.

I have designed this extension to force the constant display of the player bar at the user's request, so CPU usage is inevitably higher than when the extension is disabled.

I plan to release a version with minor performance tuning later, but the amount of CPU usage that can be reduced is very minimal.

**Comment by rsyqvthv** [comment]
@1natsu172 Thanks for your detailed explaination, yes, I can confirm that without this extension, when mouse over video to keep the youtube process bar shows, the cpu is doubled. So I would say it's not this extension's issue.

Would love to have something you can adjust even for minor improving. 

Thanks for your prompt response for all our issue report and get things fixed. 
you are a brilliant developer!

**Comment by 1natsu172** [comment]
I have submitted version 3.0.5 for review to the store. This update optimizes the CPU usage caused by this extension.

Thank you for the report.
