### ISSUE TITLE
オプションの提供

### ISSUE THREAD

**Issue by 1natsu172** [1natsu172/Outside-YouTube-Player-Bar#63]
- [x] default behavior
- [x] player bar to be hide or blockhide
- [x] when fullscreen behavior
- [x] escape hatch

**Comment by tyoropin** [comment]
> when fullscreen behavior

I agree with him.
I used to find it easier to see the bottom edge of the video when changing to full screen because it was not hidden.
However, since the update, the player bar covers the video every time I change to full screen and I have to press a button to change the display position each time.
I would appreciate it if you could fix this as soon as possible, because I think the people who use this extension are people (like me) who can't stand even the slightest frustration and try to erase it.

**Comment by 1natsu172** [comment]
Sorry but the current behavior is correct in v3. Also the extensions are published what I am making for myself. In other words, it's just a sharing. Not all users needs can be covered by v3.

This Issue is a roadmap for v4 development. v4 will be full scratch and everything will be reimplemented. Because the current code has too much technical debt to add any more features.

This is a non-business project and I will not be able to support v4 anytime soon. I have to do it little by little by cutting back on my personal time.

(This extension is OSS, so you can fork this repo and customize it yourself.)

**Comment by 1natsu172** [comment]
@tyoropin v4 has been released.
